version: 2.1

orbs:
  node: circleci/node@5.1.0
  gh-pages: sugarshin/gh-pages@1.0.1

jobs:
  deploy:
    docker:
      - image: circleci/node:20.7.0
    executor: gh-pages/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: |
          yarn build
      - gh-pages/deploy:
          build-dir: ./build

workflows:
  Publish to Github Pages:
      jobs:
        - deploy